### ISSUE TITLE
Is there a plan to make a windows build of the native libraries?

### ISSUE THREAD

**Issue by AndyAdamczak** [awslabs/amazon-kinesis-producer#1]
I do my development on windows (I run ubuntu on the real servers), so I was wondering if there was a plan to make windows binaries and include them in the KPL release in Maven?

I saw some code in the library that extracts the binaries checking for windows, so I was wondering...

Thanks

**Comment by kevincdeng** [comment]
Hi Andy,

Thanks for checking. We are working on it. It will be available in a future release.

**Comment by smartnut007** [comment]
:+1:  If it would come out in a month, we could really use it. Else, we would have to build message packing and unpacking, local buffering, batching etc on our own. Also, I assume the windows version of the binaries would be accompanied by a KPL for .Net.

**Comment by kevincdeng** [comment]
The 0.10.0 release is now [available](http://search.maven.org/#artifactdetails%7Ccom.amazonaws%7Camazon-kinesis-producer%7C0.10.0%7Cjar) and works on Windows.

Unfortunately a .NET wrapper is still in the works and I cannot provide an ETA at this point.

**Comment by stavalfi** [comment]
I''m using Windows 7 64-bit, Java 8, KPL 0.10.0.
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/stava/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/stava/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
11:37:59.075 [main] INFO com.amazonaws.services.kinesis.producer.KinesisProducer - Extracting binaries to C:\Users\stava\AppData\Local\Temp\amazon-kinesis-producer-native-binaries_419155083901459
11:38:01.366 [pool-1-thread-1] DEBUG com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
11:38:01.366 [pool-1-thread-1] DEBUG com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)
11:38:01.382 [pool-1-thread-1] DEBUG com.amazonaws.auth.AWSCredentialsProviderChain - Loading credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@3dea0e80
Exception in thread "main" java.util.concurrent.ExecutionException: com.amazonaws.services.kinesis.producer.IrrecoverableError: Unexpected error connecting to child process
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.example.awskinesesnew.NewKinesisLib.write(NewKinesisLib.java:35)
	at com.example.awskinesesnew.NewKinesisLib.main(NewKinesisLib.java:17)
Caused by: com.amazonaws.services.kinesis.producer.IrrecoverableError: Unexpected error connecting to child process
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:502)
	at com.amazonaws.services.kinesis.producer.Daemon.access$1200(Daemon.java:61)
	at com.amazonaws.services.kinesis.producer.Daemon$6.run(Daemon.java:447)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11:38:04.459 [pool-1-thread-2] ERROR com.amazonaws.services.kinesis.producer.KinesisProducer - Error in child process
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
com.amazonaws.services.kinesis.producer.IrrecoverableError: Unexpected error connecting to child process
	at java.lang.Thread.run(Thread.java:745)
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:502)
Caused by: java.nio.file.NoSuchFileException: \\.\pipe\amz-aws-kpl-in-pipe-56c3675f
	at com.amazonaws.services.kinesis.producer.Daemon.access$1200(Daemon.java:61)
	at com.amazonaws.services.kinesis.producer.Daemon$6.run(Daemon.java:447)
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.lang.Thread.run(Thread.java:745)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
Caused by: java.nio.file.NoSuchFileException: \\.\pipe\amz-aws-kpl-in-pipe-56c3675f
	at com.amazonaws.services.kinesis.producer.Daemon.connectToChild(Daemon.java:329)
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at com.amazonaws.services.kinesis.producer.Daemon.access$1000(Daemon.java:61)
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
	at com.amazonaws.services.kinesis.producer.Daemon$6.run(Daemon.java:444)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	... 5 more
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.amazonaws.services.kinesis.producer.Daemon.connectToChild(Daemon.java:329)
	at com.amazonaws.services.kinesis.producer.Daemon.access$1000(Daemon.java:61)
	at com.amazonaws.services.kinesis.producer.Daemon$6.run(Daemon.java:444)
	... 5 common frames omitted
```

**Comment by pfifer** [comment]
@stavalfi What you're seeing is a race condition that can occur in the windows version.  If you see this happening consistently, please open a new issue.
