### ISSUE TITLE
Exception during updateCredentials

### ISSUE THREAD

**Issue by jtruty** [awslabs/amazon-kinesis-producer#10]
Is it possible to avoid this error when calling producer.destroy() to end the program? It doesn't seem to cause any issues, but I always see this:
[pool-1-thread-6] WARN com.amazonaws.services.kinesis.producer.Daemon - Exception during updateCredentials
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.amazonaws.services.kinesis.producer.Daemon$5.run(Daemon.java:316)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)

**Comment by kevincdeng** [comment]
Yea that's an expected part of the termination procedure. It doesn't indicate any problems.

We'll try to get rid of the warning in the next release.

**Comment by pcurry** [comment]
Is this issue addressed yet?

**Comment by domenkosir** [comment]
If anyone is still experiencing this issue, this fixed it for me:
`kinesisProducerConfiguration.setCredentialsRefreshDelay(100)`

As I see it, the [thread running updateCredentials](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java#L320) gets interrupted. The default delay is 5 seconds, but during shutdown the executor only waits [1 second](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java#L511) before interrupting the thread. So setting the delay to something smaller that 1 second should fix the issue.

**Comment by pfifer** [comment]
Thanks for reporting this.  We are investigating and prioritizing the fix for this. 

For other affected by this please comment, and add reactions to assist us in prioritizing the change.

**Comment by ganeshchand** [comment]
@domenkosir ```scalakinesisProducerConfiguration.setCredentialsRefreshDelay(100) ``` worked for me.

**Comment by domenkosir** [comment]
@ganeshchand I'm glad it worked!

**Comment by cch1** [comment]
Bug still impacting me.

**Comment by aromanenko-dev** [comment]
+1 to fix this issue
