### ISSUE TITLE
Exception caused in unrelated S3 test on 0.10.0 update

### ISSUE THREAD

**Issue by jtruty** [awslabs/amazon-kinesis-producer#11]
Not sure how this is caused the by upgrade to 0.10.0, but I only started seeing this with this update:
java.lang.AbstractMethodError: com.amazonaws.services.s3.internal.S3Signer.sign(Lcom/amazonaws/SignableRequest;Lcom/amazonaws/auth/AWSCredentials;)

**Comment by jtruty** [comment]
Ah, I believe it's related to the new aws-java-sdk-core dependency.

**Comment by jtruty** [comment]
Confirmed, removing the transitive dependency fixes this issue.

**Comment by kevincdeng** [comment]
Hi jtruty,

Was your S3 SDK the same version as the SDK core used in the KPL (1.9.37)? The 1.10.x SDK components are not compatible with the 1.9.x ones.

**Comment by jtruty** [comment]
No, I was using 1.9.10 in my app, which caused weirdness.

**Comment by kevincdeng** [comment]
Was that the entire stack trace? Can you paste the rest of it if there's more?

**Comment by jtruty** [comment]
This is the full stacktrace when *not* excluding:

exclude group: 'com.amazonaws', module: 'aws-java-sdk-core'

java.lang.AbstractMethodError:
com.amazonaws.services.s3.internal.S3Signer.sign(Lcom/amazonaws/SignableRequest;Lcom/amazonaws/auth/AWSCredentials;)V
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:687)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3699)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1434)
	at com.trendkite.news.wire.indexer.S3Archiver.archive(S3Archiver.java:70)
	at com.trendkite.news.wire.indexer.Indexer.index(Indexer.java:65)
	at com.trendkite.news.wire.TestArchiver.testArchiveArticle(TestArchiver.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)

**Comment by pfifer** [comment]
Using a different version of the core, and the clients can cause this behavior.  Is this still a problem with the newer release?

Please re-open this if it's still a problem.

Thanks
