### ISSUE TITLE
producer native binary missing for windows from kpl 0.12.0 and above causing crash while trying to create the producer

### ISSUE THREAD

**Issue by sshrivastava-incontact** [awslabs/amazon-kinesis-producer#113]
kenesis_producer.exe which is supposed to be packaged in amazon-kinesis-producer-xxxx.jar under amazon-kineses-producer-native-binaries/windows/ is missing from version 0.12.0 and above, attached are the screen shots below. 

This missing binary causes the crash at (KinesisProducer.java:807), while trying to create the producer as follows

_`final KinesisProducer producer = getKinesisProducer();`_

crash is in (KinesisProducer.java:807) at the following line

```
_

> byte[] bin = IOUtils.toByteArray(
>                             this.getClass().getClassLoader().getResourceAsStream(root + "/" + os + "/" + executableName));

_
```

where it is not able to get the resource, following is the log

[

> main] INFO com.amazonaws.services.kinesis.producer.KinesisProducer - Extracting binaries to C:\Users\SASHRI~1\AppData\Local\Temp\amazon-kinesis-producer-native-binaries
> Exception in thread "main" java.lang.RuntimeException: Could not copy native binaries to temp directory C:\Users\SASHRI~1\AppData\Local\Temp\amazon-kinesis-producer-native-binaries
> 	at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:856)
> 	at com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(KinesisProducer.java:245)
> 	at com.amazonaws.samples.SampleProducer.getKinesisProducer(SampleProducer.java:174)
> 	at com.amazonaws.samples.SampleProducer.main(SampleProducer.java:180)
> Caused by: java.lang.NullPointerException
> 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
> 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
> 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
> 	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:462)
> 	at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:807)
> 	... 3 more
> 
> 
> Maven Dependency : 
> 
> <dependency>
> 			<groupId>com.amazonaws</groupId>
> 			<artifactId>amazon-kinesis-producer</artifactId>
> 			<version>0.12.5</version>
> </dependency>
> 

**KPL 0.10.2 where the binary is present**

![kpl10 2](https://cloud.githubusercontent.com/assets/26897836/26677504/ea01582a-46e9-11e7-9664-0da7e39449b1.PNG)

**KPL 0.12.5 where the binary is not present**
![kpl0 12 5](https://cloud.githubusercontent.com/assets/26897836/26677515/fb5f4c80-46e9-11e7-9212-772ae4dc2648.PNG)

**KPL 0.12.0 whith missing binary**
![kpl12 0](https://cloud.githubusercontent.com/assets/26897836/26677534/0d963210-46ea-11e7-96f0-7b5b159584b9.PNG)

**Comment by chadp123** [comment]
Apparently this documentation is no longer correct?

http://docs.aws.amazon.com/streams/latest/dev/kinesis-kpl-supported-plats.html

The Java package runs without the need to install any additional libraries on the following operating systems:

Linux distributions with kernel 2.6.18 (September 2006) and later
Apple OS X 10.9 and later
**_Windows Server 2008 and later_**

Note the KPL is 64-bit only.

**Comment by borisbsu** [comment]
From 0.12.0 release notes at https://github.com/awslabs/amazon-kinesis-producer/releases

> - Windows Support is not Available for this Version.
> 
> This version of the Kinesis Producer Library doesn't currently support windows. Windows support will be added back at a later date.

**Comment by pfifer** [comment]
Windows support was added as part of the 0.12.6 release.  

There is an occasional race condition at startup that may cause failures, but it normally resolves itself relatively quickly.  The race condition is on pipe creation, and I'm looking for a better way to manage it.
