### ISSUE TITLE
Caused by: java.util.concurrent.ExecutionException: com.amazonaws.services.kinesis.producer.UserRecordFailedException

### ISSUE THREAD

**Issue by sunilgulabani** [awslabs/amazon-kinesis-producer#114]
Trying to send message and getting this exceptions at irregular interval.

StackTrace: 
com.exception.ModelerException: com.amazonaws.services.kinesis.producer.UserRecordFailedException
	at com.kinesis.ModelerKinesisProducer.sendMessage(ModelerKinesisProducer.java:79)
	at com.kinesis.ModelerKinesisProducer.lambda$sendMessage$0(ModelerKinesisProducer.java:59)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.kinesis.ModelerKinesisProducer.sendMessage(ModelerKinesisProducer.java:56)
	at com.enums.MessageType.sendToKinesis(MessageType.java:120)
	at com.enums.MessageType.processMessage(MessageType.java:115)
	at com.enums.MessageType.lambda$static$1(MessageType.java:42)
	at com.enums.MessageType.process(MessageType.java:105)
	at com.handler.kinesis.RequestProcessor.processRequest(RequestProcessor.java:50)
	at com.handler.kinesis.RequestProcessor$$FastClassBySpringCGLIB$$95ec0c3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.advice.SupervisorAdvice.aroundAdvice(SupervisorAdvice.java:57)
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.handler.kinesis.RequestProcessor$$EnhancerBySpringCGLIB$$502a79d2.processRequest(<generated>)
	at com.handler.kinesis.KinesisRecordProcessor.processRecord(KinesisRecordProcessor.java:118)
	at com.handler.kinesis.KinesisRecordProcessor.lambda$processRecords$0(KinesisRecordProcessor.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.handler.kinesis.KinesisRecordProcessor.processRecords(KinesisRecordProcessor.java:61)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.callProcessRecords(ProcessTask.java:215)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:170)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.amazonaws.services.kinesis.producer.UserRecordFailedException
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.kinesis.ModelerKinesisProducer.sendMessage(ModelerKinesisProducer.java:71)
	... 38 more
Caused by: com.amazonaws.services.kinesis.producer.UserRecordFailedException
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler.onPutRecordResult(KinesisProducer.java:188)
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler.access$000(KinesisProducer.java:127)
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler$1.run(KinesisProducer.java:134)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more

**Comment by bschrameckSila** [comment]
We got the same error the other day in our Development and our Production environments at the same time. Is it possible there is something that causes this server-side?

Additionally, after this error, we started getting errors that "the security token included in the request is expired", but we are using static credentials that never expire. We had to restart our producers to fix the issue.

Any ideas?
