### ISSUE TITLE
Could not deserialize config: Input is not valid hexadecimal

### ISSUE THREAD

**Issue by bowenli86** [awslabs/amazon-kinesis-producer#123]
Hi,
We are using KPL to write serialized objects to Kinesis, and running the following issue:

```
 INFO [kpl-daemon-0000] (Daemon.java:421) - Asking for trace
DEBUG [kpl-daemon-0000] (Daemon.java:433) - Starting Native Process: /var/folders/84/d9dx_03d7j13r7r51z7l37dc0000gp/T/amazon-kinesis-producer-native-binaries/kinesis_producer_f9d71c9bec76750d408090c32579f8982b478d68 -o /var/folders/84/d9dx_03d7j13r7r51z7l37dc0000gp/T/amazon-kinesis-producer-native-binaries/amz-aws-kpl-out-pipe-8df02fe7 -i /var/folders/84/d9dx_03d7j13r7r51z7l37dc0000gp/T/amazon-kinesis-producer-native-binaries/amz-aws-kpl-in-pipe-de894330 -c 08003279080110FFFFFFFF0F18809003220028BB0330F403388080C00240F02E480050005A0060BB036A04696E666F70187A05736861726482010864657461696C65648A010D4B504C5F42656E63686D61726B9001E0D403980101A0019601A80164B001B0EA01BA010975732D656173742D31C001F02EC80101D00100 -k 08FFFFFFFFFFFFFFFF7F4A44080012400A14414B49414A42564E4A4F5456554756324C46425112282B723532424C46786C424E5334486A4E4136346F316E6371534F324B47752F375863634A42337347 -t -w 08FFFFFFFFFFFFFFFF7F4A44080112400A14414B49414A42564E4A4F5456554756324C46425112282B723532424C46786C424E5334486A4E4136346F316E6371534F324B47752F375863634A42337347
 WARN [kpl-daemon-0003] (Daemon.java:467) - [2017-08-23 21:11:49.158923] [0x00007fffb644c3c0] [error] [main.cc:71] Could not deserialize config: Input is not valid hexadecimal
ERROR [kpl-daemon-0000] (KinesisProducer.java:152) - Error in child process
com.amazonaws.services.kinesis.producer.IrrecoverableError: Child process exited with code 1
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:525)
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:497)
	at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:475)
	at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:63)
	at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:133)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

What does "Could not deserialize config: Input is not valid hexadecimal" mean? Anything wrong with the serialization?

Thanks

**Comment by bowenli86** [comment]
I'm running on Mac with java version "1.8.0_111". Temp files like `/var/folders/84/d9dx_03d7j13r7r51z7l37dc0000gp/T/amazon-kinesis-producer-native-binaries/xxxx` were successfully created.
