### ISSUE TITLE
KPL with Lambda

### ISSUE THREAD

**Issue by jayapaul** [awslabs/amazon-kinesis-producer#195]
I'm using KPL 0.12.8 and AWS Lambda to read data from a kinesis stream and publish it to a stream in another account.
```
Exception during put: 
com.amazonaws.services.kinesis.producer.IrrecoverableError: Pipes did not show up after calling mkfifo
at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:525)
at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:497)
at com.amazonaws.services.kinesis.producer.Daemon.createPipesUnix(Daemon.java:406)
at com.amazonaws.services.kinesis.producer.Daemon.createPipes(Daemon.java:359)
at com.amazonaws.services.kinesis.producer.Daemon.access$000(Daemon.java:63)
at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:132)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by bisoldi** [comment]
Did you ever get anywhere with this?  I'm working on implementing the KPL within Lambda and found this doing a basic search.  I wonder if it's because of the native code within the KPL?
