### ISSUE TITLE
KPL 0.12.9 crashes Lambda with "No space left on device"

### ISSUE THREAD

**Issue by msanjose** [awslabs/amazon-kinesis-producer#204]
We're testing KPL 0.12.9 (upgraded from 0.12.8) with one of our Lambda functions and we immediately started getting exceptions that indicate the local disk is full:

```Could not copy native binaries to temp directory /tmp/amazon-kinesis-producer-native-binaries: java.lang.RuntimeException
java.lang.RuntimeException: Could not copy native binaries to temp directory /tmp/amazon-kinesis-producer-native-binaries
at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:907)
at com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(KinesisProducer.java:245)
at com.comcast.deap.KinesisAggregatorLambda.getKinesisProducer(KinesisAggregatorLambda.java:107)
at com.comcast.deap.KinesisAggregatorLambda.handleRequest(KinesisAggregatorLambda.java:151)
at com.comcast.deap.KinesisAggregatorLambda.handleRequest(KinesisAggregatorLambda.java:37)

Caused by: java.io.IOException: No space left on device
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:326)
at java.security.DigestOutputStream.write(DigestOutputStream.java:145)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
at com.amazonaws.services.kinesis.producer.HashedFileCopier.copyFileFrom(HashedFileCopier.java:52)
at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:893)
... 4 more```

Any suggestions on a workaround or best practices running KPL within a Lambda? Would it be a good idea to start deleting `/tmp/*` whenever our lambdas are invoked?

**Comment by pfifer** [comment]
The KPL needs to hash the binary data to figure out if the binary was actually extracted.  So it extracts the data to a temporary file while it calculates the hash.  If the binary isn't present it will rename the extracted file to the expected filename.  During extraction it may need double the space.  The Linux binary is 41 MB so during extraction it may need at least 82 MB.  Also the KPL isn't good about cleaning up earlier versions of the binary, so cleaning the tmp directory might help in that case.

I'll look into adding a configuration that will allow it to calculate the hash without extracting the binary to disk, but it could take a bit longer during the extraction process as it will make two passes.
