### ISSUE TITLE
"EOF reached during read" error

### ISSUE THREAD

**Issue by justinborromeo-toast** [awslabs/amazon-kinesis-producer#210]
I'm running a service that writes records to a Kinesis stream.  When it tries to write (by calling `addUserRecord`), it fails and receives the following exception:
```
 java.lang.RuntimeException: EOF reached during read
! at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:533) ~[toast-ccfile-processing-application-90-all.jar:na]
! at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:509) ~[toast-ccfile-processing-application-90-all.jar:na]
! at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:505) ~[toast-ccfile-processing-application-90-all.jar:na]
! at com.amazonaws.services.kinesis.producer.Daemon.readSome(Daemon.java:554) ~[toast-ccfile-processing-application-90-all.jar:na]
! at com.amazonaws.services.kinesis.producer.Daemon.receiveMessage(Daemon.java:246) ~[toast-ccfile-processing-application-90-all.jar:na]
! at com.amazonaws.services.kinesis.producer.Daemon.access$500(Daemon.java:63) ~[toast-ccfile-processing-application-90-all.jar:na]
! at com.amazonaws.services.kinesis.producer.Daemon$3.run(Daemon.java:301) ~[toast-ccfile-processing-application-90-all.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

Any suggestions on how to fix?

**Comment by twosider** [comment]
This is the message that Java sends when the underlying C++ daemon exits and closes the pipe. Above this in the logs, you should see some errors coming from the C++ daemon. Can you confirm that the server can connect to Kinesis? tcpdump or strace might be a quick way to rule out some possibilities. Otherwise gdb might be needed.

**Comment by justinborromeo-toast** [comment]
The issue was that it wasn't connection to Kinesis.  Closing this issue.
