### ISSUE TITLE
Error starting KPL java.lang.RuntimeException: Could not copy native binaries to temp directory /tmp/amazon-kinesis-producer-native-binaries

### ISSUE THREAD

**Issue by ChengzhiZhao** [awslabs/amazon-kinesis-producer#251]
I am trying to test KPL by building a uber jar from master, however, after I clone the repo and I did `mvn package` I got the following errors on test, I wonder if anyone faces this before and how you build the package. Thanks!

```2019-03-19 18:02:41,419 [pool-1-thread-5] ERROR c.a.s.k.producer.KinesisProducerTest [NONE] - Error starting KPL
java.lang.RuntimeException: Could not copy native binaries to temp directory /tmp/amazon-kinesis-producer-native-binaries
	at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:908)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(KinesisProducer.java:245)
	at com.amazonaws.services.kinesis.producer.KinesisProducerTest.getProducer(KinesisProducerTest.java:221)
	at com.amazonaws.services.kinesis.producer.KinesisProducerTest.access$000(KinesisProducerTest.java:47)
	at com.amazonaws.services.kinesis.producer.KinesisProducerTest$1.run(KinesisProducerTest.java:185)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at com.amazonaws.services.kinesis.producer.HashedFileCopier.copyFileFrom(HashedFileCopier.java:52)
	at com.amazonaws.services.kinesis.```

**Comment by krishnaputhran** [comment]
I face the same issue, not sure how to come across this problem? ChengzhiZhao did you got any fix for this?

**Comment by ChengzhiZhao** [comment]
@krishnaputhran I got it fixed by adding the `amazon-kinesis-producer-native-binaries` back. 
https://github.com/awslabs/amazon-kinesis-producer/blob/21e192ac83c608b27a57b427015bb87c751c5f2a/.gitignore#L4
It's a kind hack, you can put it back by unzipping an existing KPL lib

**Comment by krishnaputhran** [comment]
Thank you. It worked

**Comment by alajay123** [comment]
I do not see it in .gitignore an still see same error..Any other solutions for this..?

**Comment by ssgaur** [comment]
I am facing above problem in 0.12.9 to 0.12.11. below is log

`com.amazonaws.services.kinesis.producer.IrrecoverableError: Error starting child process
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:537)
	at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:468)
	at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:63)
	at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "/tmp/amazon-kinesis-producer-native-binaries/kinesis_producer_489FA9AC71B1CD61A4002E9F16A279556D581D9D": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:466)
	... 5 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 common frames omitted`

**Comment by abhinav-balraj** [comment]
is

**Comment by harshkhanna** [comment]
> issue is still there
> 
> Exception in thread "main" java.lang.RuntimeException: Could not copy native binaries to temp directory /var/folders/n1/0kxh3sn134v3f61sy_y26k8m0000gq/T/amazon-kinesis-producer-native-binaries
> at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:908)
> at com.amazonaws.services.kinesis.producer.KinesisProducer.(KinesisProducer.java:245)
> at com.amazonaws.services.kinesis.producer.sample.SampleProducer.main(SampleProducer.java:87)
> Caused by: java.lang.NullPointerException
> at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
> at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
> at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
> at com.amazonaws.services.kinesis.producer.HashedFileCopier.copyFileFrom(HashedFileCopier.java:52)
> at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:894)

Any fix for this?

**Comment by benkusak** [comment]
+1 Issue Remains

**Comment by computrade** [comment]
I'm facing the same issue with all 0.14.* version.
With previous version 0.13.1 for example it works.

Any simple solution for that?

**Comment by cobar79** [comment]
0.13.1 throws org.apache.commons.io.Charsets ClassNotFound on startup even if Charsets is in jar?

**Comment by chandanjonson** [comment]
> I am trying to test KPL by building a uber jar from master, however, after I clone the repo and I did `mvn package` I got the following errors on test, I wonder if anyone faces this before and how you build the package. Thanks!
> 
> ```
> java.lang.RuntimeException: Could not copy native binaries to temp directory /tmp/amazon-kinesis-producer-native-binaries
> 	at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:908)
> 	at com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(KinesisProducer.java:245)
> 	at com.amazonaws.services.kinesis.producer.KinesisProducerTest.getProducer(KinesisProducerTest.java:221)
> 	at com.amazonaws.services.kinesis.producer.KinesisProducerTest.access$000(KinesisProducerTest.java:47)
> 	at com.amazonaws.services.kinesis.producer.KinesisProducerTest$1.run(KinesisProducerTest.java:185)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException: null
> 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
> 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
> 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
> 	at com.amazonaws.services.kinesis.producer.HashedFileCopier.copyFileFrom(HashedFileCopier.java:52)
> 	at com.amazonaws.services.kinesis.```
> ```

@krishnaputhran is it worked for you?
