### ISSUE TITLE
KPL throws continuously exception and creates child processes until fills the RAM of the server

### ISSUE THREAD

**Issue by vvararu** [awslabs/amazon-kinesis-producer#261]
Using KPL as flink job producer. After the start of the job KPL library starts to continuously log exceptions and create child java processes without killing old ones until the server remains out of memory.

Server OS: Ubuntu 16.04.1 LTS

**Do not reproduce** on amazon-kinesis-producer 0.12.9.

**Reproduced on** amazon-kinesis-producer **0.12.11** with exception
```
2019-06-06 06:50:43,604 ERROR org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.KinesisProducer  - Error in child process
java.lang.RuntimeException: Child process exited with code 139
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:533)
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:509)
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:487)
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:63)
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-06 06:50:43,605 INFO  org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.KinesisProducer  - Restarting native producer process.
```

**Reproduced on** amazon-kinesis-producer **0.12.10** with exception
```
2019-06-06 06:44:54,389 ERROR org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.KinesisProducer  - Error in child process
org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.IrrecoverableError: Child process exited with code 1
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:537)
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:509)
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:487)
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:63)
	at org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-06 06:44:54,392 INFO  org.apache.flink.kinesis.shaded.com.amazonaws.services.kinesis.producer.KinesisProducer  - Restarting native producer process.
```

**Comment by ptdang** [comment]
@vvararu what `ThreadingModel` did you use?
