### ISSUE TITLE
0.10.0 Introduces "Could not retrieve credentials from anywhere" on any type of credentials provider

### ISSUE THREAD

**Issue by lc-nyovchev** [awslabs/amazon-kinesis-producer#27]
I have the simplest case of a producer, one that gets 

Config either from a `StaticCredentialsProvider`,
or a `ClassPathCredentialsProviderr` and I place the AwsCredentials.properties file in the classpath. Or a `DefaultCredentialsProvider` and specify the  

``` java
System.setProperty("aws.secretKey", "XXX"); 
System.setProperty("aws.accessKeyId", "XXXX");
```

But every time I get the error in the daemon:
Could not retrieve credentials from anywhere

Seems like the args to the process builder are not correctly passed? Here is stack trace, not that it helps:

``` java
[2015-10-12 23:54:26.443458] [0x00007f5cb52dc780] [error] [main.cc:156] Could not retrieve credentials from anywhere.
[pool-2-thread-1] ERROR com.amazonaws.services.kinesis.producer.KinesisProducer - Error in child process
com.amazonaws.services.kinesis.producer.IrrecoverableError: Child process exited with code 1
    at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:502)
    at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:480)
    at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:460)
    at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:61)
    at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:128)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:744) 
```

Debugging shows that regardless which credentials provider I specify, it always is done correctly on the java side, but then things get messy during the process builder protobuffing the last argument to the process for the accessKey and the secretKey. This is always reproducible and happens on **0.10.0** and **0.10.1**

**Comment by eboto** [comment]
Also encountering this issue. Verified on both linux and osx.

**Comment by eboto** [comment]
@lc-nyovchev this may be happening because your secrets aren't passing this library's internal validation. Internally it seems to validate that the access key is 20 chars and the secret key is 40. However it swallows that error and instead says that it couldn't find credentials. Specifically, I believe that our code is failing [here](https://github.com/awslabs/amazon-kinesis-producer/blob/e08c08c9fff4a101ee506bca2589bc92cecb8a4c/aws/auth/credentials.cc#L30), then that exception gets swallowed without logging [here](https://github.com/awslabs/amazon-kinesis-producer/blob/e08c08c9fff4a101ee506bca2589bc92cecb8a4c/aws/auth/credentials.cc#L39) and only ends up producing the not-that-useful log [here](https://github.com/awslabs/amazon-kinesis-producer/blob/e08c08c9fff4a101ee506bca2589bc92cecb8a4c/aws/kinesis/main.cc#L156)

try verifying that your keys actually match [these regexes](https://github.com/awslabs/amazon-kinesis-producer/blob/e08c08c9fff4a101ee506bca2589bc92cecb8a4c/aws/auth/credentials.cc#L43)?

**Comment by lc-nyovchev** [comment]
Yes the credentials I passed did pass the regexes (one of the configProviders even checked for that) but the account was not correctly authorized for Kinesis so that could be it. However, the swallowing of exceptions is not really nice, would be nice if it actually properly identifies what is the cause of the daemon falling.

**Comment by pfifer** [comment]
This may no longer be an issue with the 0.12.x versions of the KPL.  It uses the AWS C++ SDK that should provide more complete error messages.  I just ran a test using a user without access to Kinesis:
```
2017-02-15 08:36:11,229 [kpl-daemon-0003] WARN  c.a.s.k.p.LogInputStreamReader [NONE] - [2017-02-15 08:36:11.229239] [0x00009d6b][0x0000700005ee0000] [warning] [AWS Log: WARN](AWSErrorMarshaller)Encountered AWSError
AccessDeniedException
User: arn:aws:iam::xxx:user/no-kinesis is not authorized to perform: kinesis:PutRecords on resource: arn:aws:kinesis:us-west-2:xxx:stream/kinesis-local-eco-test:
```

Please feel free to reopen if you have further issues or questions.

**Comment by jayapaul** [comment]
I'm using KPL 0.12.8. 

```
Exception during put: 
com.amazonaws.services.kinesis.producer.IrrecoverableError: Pipes did not show up after calling mkfifo
at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:525)
at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:497)
at com.amazonaws.services.kinesis.producer.Daemon.createPipesUnix(Daemon.java:406)
at com.amazonaws.services.kinesis.producer.Daemon.createPipes(Daemon.java:359)
at com.amazonaws.services.kinesis.producer.Daemon.access$000(Daemon.java:63)
at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:132)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```
