### ISSUE TITLE
KPL version 0.14.13 is broken

### ISSUE THREAD

**Issue by spsheni** [awslabs/amazon-kinesis-producer#453]
Last week we updated from version 0.14.12 to 0.14.13.

When application tries to call `addUserRecord`, KPL throws exception `com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.` and then tries to restart. And the restart fails with below log details,

```
[2022-10-10 10:26:47.233 +0000] [kpl-daemon-0000] E| c.a.s.k.producer.KinesisProducer - Error in child process java.lang.RuntimeException: Child process exited with code 127 at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:532) at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:508) at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:486) at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:61) at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:130) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)

[2022-10-10 10:26:47.255 +0000] [kpl-daemon-0003] W| c.a.s.k.producer.LogInputStreamReader - /opt/tomcat/temp/amazon-kinesis-producer-native-binaries/kinesis_producer_B2A87159E60ABF99DE719370CD9483CFC815BAC9: error while loading shared libraries: libuuid.so.1: cannot open shared object file: No such file or directory
```

Our application is running in Alpine image, here is output from cmdline,
```
bash-5.1$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.2
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

Kindly acknowledge the issue is in KPL.

Currently I am forced to use the previous version.

**Comment by lbourdages** [comment]
I am running into the same issue. Using the `adoptopenjdk/openjdk11:alpine-jre` image with mininal changes.

**Comment by lc-nyovchev** [comment]
@lbourdages and @spsheni is it possible that the issue you experience is the same as the one described here: https://github.com/awslabs/amazon-kinesis-producer/issues/452 ?

**Comment by spsheni** [comment]
@lc-nyovchev , No. I have copied the stack trace in above bug description section. Issue here is around 'error while loading shared libraries: libuuid.so'
