### ISSUE TITLE
KPL version 0.15.0 - Error in child process

### ISSUE THREAD

**Issue by bschev** [awslabs/amazon-kinesis-producer#467]
Hello, I updated from version 0.14.13 to 0.15.0. 

The update resulted in failures of the child process when creating the KinesisProducer:

```
2023-01-09 08:13:51,448 INFO c.a.s.k.p.KinesisProducer [main] Extracting binaries to /tmp/amazon-kinesis-producer-native-binaries
2023-01-09 08:13:56,452 ERROR c.a.s.k.p.KinesisProducer [kpl-daemon-0000] Error in child process com.amazonaws.services.kinesis.producer.IrrecoverableError: Child process exited with code 1
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:538)
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:508)
	at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:486)
	at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:61)
	at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:130)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
 {} []
2023-01-09 08:13:56,482 INFO c.a.s.k.p.KinesisProducer [kpl-daemon-0000] Restarting native producer process.  {} []
2023-01-09 08:13:57,468 ERROR c.a.s.k.p.KinesisProducer [kpl-daemon-0000] Error in child process com.amazonaws.services.kinesis.producer.IrrecoverableError: Child process exited with code 1
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:538)
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:508)
	at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:486)
	at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:61)
	at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:130)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
 {} []
2023-01-09 08:13:57,498 INFO c.a.s.k.p.KinesisProducer [kpl-daemon-0000] Restarting native producer process.  {} []
...
```

OS: Amazon Linux 2

Where can I find out more about the error causing the child process to fail?

**Comment by zengyu714** [comment]
Hi bschev@, a new patch version will be released by this week to address the issue, thanks for reporting the error!
