### ISSUE TITLE
FileLockInterruptionException when extracting native binaries

### ISSUE THREAD

**Issue by eoconnor** [awslabs/amazon-kinesis-producer#55]
I see these exceptions frequently when my code first attempts to instantiate a KinesisProducer instance:

```
java.lang.RuntimeException: Could not copy native binaries to temp directory /tmp/amazon-kinesis-producer-native-binaries
        at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:826)
        at com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(KinesisProducer.java:236)
        at com.mypackage.MyKinesisWriter.run(MyKinesisWriter.java:32)
        at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
        at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
        at rx.Observable$1.call(Observable.java:145)
        at rx.Observable$1.call(Observable.java:137)
        at rx.Observable$1.call(Observable.java:145)
        at rx.Observable$1.call(Observable.java:137)
        at rx.Observable$1.call(Observable.java:145)
        at rx.Observable$1.call(Observable.java:137)
        at rx.Observable.unsafeSubscribe(Observable.java:7713)
        at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:534)
        at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:509)
        at rx.Observable.unsafeSubscribe(Observable.java:7713)
        at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
        at com.nike.trace.hystrix.TraceCallableWrapper.call(TraceCallableWrapper.java:32)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.FileLockInterruptionException
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1071)
        at java.nio.channels.FileChannel.lock(FileChannel.java:1052)
        at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:818)
        ... 27 more
```

I've got a synchronized block around the method from which I'm calling the KinesisProducer constructor in an effort to make it thread-safe, but that doesn't help. I've also tried configuring my KinesisProducerConfiguration instance with a unique pathname to avoid file collisions, but I still get the above exception. I've done some Googling but haven't found any instances of anyone else reporting this error. My code attempts to re-try initialization of the KinesisProducer instance when this exception occurs, but it happens multiple times in a row.

Some other things to point out:

- The class running this code is run using Hystrix
- The application that is running this code is run in a cluster, and interestingly, I've noticed that this error will often only affect a single node in the cluster.

**Comment by pfifer** [comment]
This sort of looks like two different processes running at the same time.  Unfortunately the KPL extracts the binaries to the same location, so two different processes could conflict with each other.  

It's not recommended to create more than one KinesisProducer instance since each one will attempt to create a new native process.  The KinesisProducer instance is thread safe, and should be shareable.
