### ISSUE TITLE
Cannot run program "/tmp/amazon-kinesis-producer-native-binaries/kinesis_producer_A123FCDFBE0C056D71AF4EE4DC5DE0A6A8AFA68C": error=2, No such file or directory

### ISSUE THREAD

**Issue by iduanyingjie** [awslabs/amazon-kinesis-producer#568]
running on docker
```Java
com.amazonaws.services.kinesis.producer.IrrecoverableError: Error starting child process
        at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:535) [amazon-kinesis-producer-0.15.10.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:466) [amazon-kinesis-producer-0.15.10.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:60) [amazon-kinesis-producer-0.15.10.jar:?]
        at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:129) [amazon-kinesis-producer-0.15.10.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.io.IOException: Cannot run program "/tmp/amazon-kinesis-producer-native-binaries/kinesis_producer_A123FCDFBE0C056D71AF4EE4DC5DE0A6A8AFA68C": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143) ~[?:?]
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073) ~[?:?]
        at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:464) ~[amazon-kinesis-producer-0.15.10.jar:?]
        ... 5 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314) ~[?:?]
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244) ~[?:?]
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110) ~[?:?]
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073) ~[?:?]
        at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:464) ~[amazon-kinesis-producer-0.15.10.jar:?]
        ... 5 more
```

But this execute file obviously exists

```bash
user@host amazon-kinesis-producer-native-binaries]$ ll
total 70348
drwxr-xr-x 2 root root     4096 Apr 29 02:49 cacerts
-rw-r--r-- 1 root root        0 Apr 29 02:49 cacerts.lock
-rwxr--r-- 1 root root 72030786 Apr 29 02:49 kinesis_producer_A123FCDFBE0C056D71AF4EE4DC5DE0A6A8AFA68C
-rw-r--r-- 1 root root        0 Apr 29 02:49 kinesis_producer_A123FCDFBE0C056D71AF4EE4DC5DE0A6A8AFA68C.lock
```

**Comment by iduanyingjie** [comment]
Change Dockerfile
`FROM amazoncorretto:17-alpine`
To
`FROM eclipse-temurin:17`
