### ISSUE TITLE
[BUG]: Protobuf incompatibility with the KCL

### ISSUE THREAD

**Issue by etspaceman** [awslabs/amazon-kinesis-producer#608]
Seems there was an upgrade of Protobuf in the [3.0.0 version of the KCL](https://github.com/awslabs/amazon-kinesis-client/blob/v3.0.0/amazon-kinesis-client/pom.xml#L51). Unfortunately, I discovered this because upgrading to the 3.0.0 KCL produces a new error for Protobuf when the KPL is also in use in the same project. I believe this is because the KPL is on [3.25.5](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/pom.xml#L79C7-L79C8).

https://github.com/etspaceman/kinesis-mock/pull/942 is the PR in my project to upgrade the KCL to 3.0.0. The error: 

```
Error: Exception in thread "kpl-daemon-0005" java.lang.NoSuchMethodError: 'void com.amazonaws.services.kinesis.producer.protobuf.Messages$Message.makeExtensionsImmutable()'
	at com.amazonaws.services.kinesis.producer.protobuf.Messages$Message.<init>(Messages.java:3447)
	at com.amazonaws.services.kinesis.producer.protobuf.Messages$Message.<init>(Messages.java:3280)
	at com.amazonaws.services.kinesis.producer.protobuf.Messages$Message$1.parsePartialFrom(Messages.java:5434)
	at com.amazonaws.services.kinesis.producer.protobuf.Messages$Message$1.parsePartialFrom(Messages.java:5428)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:77)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:97)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:102)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:25)
	at com.amazonaws.services.kinesis.producer.protobuf.Messages$Message.parseFrom(Messages.java:3995)
	at com.amazonaws.services.kinesis.producer.Daemon.receiveMessage(Daemon.java:253)
	at com.amazonaws.services.kinesis.producer.Daemon.access$500(Daemon.java:60)
	at com.amazonaws.services.kinesis.producer.Daemon$3.run(Daemon.java:297)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

I would think the best path forward is to upgrade Protobuf in the KPL to match what is in the KCL and provide a new release.

**Comment by mpviau** [comment]
Facing same issue here.

**Comment by mpviau** [comment]
Also now imcompatible with KCL 2.6.1 which also bumped protobuf.

**Comment by chenylee-aws** [comment]
Protobuf version is bumped in KPL release 1.0.0

**Comment by etspaceman** [comment]
@chenylee-aws I don't see 1.0.0 on maven:

https://mvnrepository.com/artifact/com.amazonaws/amazon-kinesis-producer

**Comment by minuhong-aws** [comment]
@etspaceman Yes, we changed the package name / groupId in KPL 1.0.0 to align with the AWS SDK v2 naming convention (from com.amazonaws.xxx to software.amazon.xxx).

**Comment by CyrilDevOps** [comment]
we are at kcl 2.5.34 and kpl 0.15.12,
what is our steps to upgrade to kcl 2.70. and kpl 1.0.1 and keeping compatibility with the in-fly-message in kinesis during our deployment ?

Is there a matrix of compatibility between kpl and kcl ?
