### ISSUE TITLE
Could not configure the region. It was not given in the config and we were unable to retrieve it from EC2 metadata.

### ISSUE THREAD

**Issue by charany1** [awslabs/amazon-kinesis-producer#87]
Version : amazon-kinesis-producer : 0.12.1

Envrionment : Running inside a ubuntu-docker container .

I've a pretty simple config : 

`public static final String REGION = "us-east-1";
final static KinesisProducer kinesisProducer;
	static {
		KinesisProducerConfiguration config = new KinesisProducerConfiguration(); 
		config.setRegion(REGION);   
         kinesisProducer = new KinesisProducer(config);
	}`
 I'm getting this error : 

`com.amazonaws.services.kinesis.producer.IrrecoverableError: Child process exited with code 1
        at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:520) [application.jar:0.1]
        at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:492) [application.jar:0.1]
        at com.amazonaws.services.kinesis.producer.Daemon.startChildProcess(Daemon.java:475) [application.jar:0.1]
        at com.amazonaws.services.kinesis.producer.Daemon.access$100(Daemon.java:62) [application.jar:0.1]
        at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:132) [application.jar:0.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

2016-12-23 08:00:42.434 UTC  INFO rid=12788780-78ee-49cf-8570-24d66bd01c1b cid=NA 1 --- [kpl-daemon-0000] c.a.s.kinesis.producer.KinesisProducer   : Restarting native producer process.
2016-12-23 08:00:42.447 UTC  INFO rid=12788780-78ee-49cf-8570-24d66bd01c1b cid=NA 1 --- [kpl-daemon-0000] c.a.services.kinesis.producer.Daemon     : Asking for trace
2016-12-23 08:00:42.450 UTC  INFO rid=12788780-78ee-49cf-8570-24d66bd01c1b cid=NA 1 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2016-12-23 08:00:42.450062] [0x00000087][0x00007f995dd
f9780] [info] [logging.cc:83] Set boost log level to info
2016-12-23 08:00:42.450 UTC  INFO rid=12788780-78ee-49cf-8570-24d66bd01c1b cid=NA 1 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2016-12-23 08:00:42.450153] [0x00000087][0x00007f995dd
f9780] [info] [logging.cc:170] Set AWS Log Level to WARN
2016-12-23 08:00:43.454 UTC ERROR rid=12788780-78ee-49cf-8570-24d66bd01c1b cid=NA 1 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2016-12-23 08:00:43.454018] [0x00000087][0x00007f995dd
f9780] [error] [AWS Log: ERROR](CurlHttpClient)Curl returned error code 28
2016-12-23 08:00:43.454 UTC ERROR rid=12788780-78ee-49cf-8570-24d66bd01c1b cid=NA 1 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2016-12-23 08:00:43.454320] [0x00000087][0x00007f995dd
f9780] [error] [AWS Log: ERROR](EC2MetadataClient)Http request to Ec2MetadataService failed.

2016-12-23 08:00:43.456 UTC ERROR rid=12788780-78ee-49cf-8570-24d66bd01c1b cid=NA 1 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2016-12-23 08:00:43.455972] [0x00000087][0x00007f995dd
f9780] [error] [main.cc:266] Could not configure the region. It was not given in the config and we were unable to retrieve it from EC2 metadata.
2016-12-23 08:00:43.469 UTC  INFO rid=12788780-78ee-49cf-8570-24d66bd01c1b cid=NA 1 --- [kpl-daemon-0002] c.a.s.k.producer.LogInputStreamReader    : Received IO Exception during shutdown.  This can happen
, but should indicate that the stream has been closed: Stream Closed`

**Comment by charany1** [comment]
I was behind a proxy , removed that , it worked .
